# Generated by Django 4.0.4 on 2022-05-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='uuid',
            new_name='user_uuid',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='username',
        ),
        migrations.AddField(
            model_name='accounts',
            name='account_balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accounts',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
